#!/bin/sh
#
# Copyright 2023 Brian Pursley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

tmpfile=$(mktemp /tmp/kubectl-quick.XXXXXX)

cleanup() {
  rm $tmpfile
}
trap cleanup EXIT

while : 
do
  $EDITOR $tmpfile 

  if [ -s $tmpfile ]; then
    if kubectl apply -f $tmpfile; then
      exit 0 
    fi
  else
    exit 0
  fi

  echo
  read -p 'Do you want to retry (Y/n)?' retry
  if [ "$retry" = "n" ]; then
    exit 1
  fi
  echo
done

